# Generated by Django 5.1.2 on 2024-11-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ManyToManyField(related_name='games', to='Games.publisher'),
        ),
    ]
