# Generated by Django 5.1.2 on 2024-11-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_rename_onpc_game_onwindows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
