# Generated by Django 5.1.2 on 2024-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0004_alter_game_title_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(unique=True),
        ),
    ]
