# Generated by Django 5.1.2 on 2024-11-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='onPs',
        ),
        migrations.RemoveField(
            model_name='game',
            name='onSwitch',
        ),
        migrations.RemoveField(
            model_name='game',
            name='onXbox',
        ),
    ]
