# Generated by Django 5.1.2 on 2024-11-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_remove_game_onps_remove_game_onswitch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='onPc',
            new_name='onWindows',
        ),
    ]
